### ISSUE TITLE
Fix offline transaction signing

### ISSUE THREAD

**Issue by crocket** [haven-protocol-org/haven-offshore#13]
For now, signing a transaction offline requires online price because it is required for XHV<->xUSD conversion.

**Comment by crocket** [comment]
It seems to be already fixed.

**Comment by crocket** [comment]
I reopen this because it is not actually fixed.

`sign_transfer` leads to `Failed to get pricing record` error on an offline machine.

**Comment by goshiz** [comment]
It's not possible to sign_transfer an offline transaction involving a mint/burn since the wallet need to check the math behind the transaction and need the price record to do so. We have an issue open to remove the PR check in case of a simple transfer.

**Comment by crocket** [comment]
Can you not make `submit_transfer` check the prices?

**Comment by crocket** [comment]
I applied this patch

```
diff -ur haven-offshore-1.3.0c/monero/src/wallet/wallet2.cpp haven-offshore-1.3.0c-new/monero/src/wallet/wallet2.cpp
--- haven-offshore-1.3.0c/monero/src/wallet/wallet2.cpp	2021-04-19 23:17:17.293191935 +0900
+++ haven-offshore-1.3.0c-new/monero/src/wallet/wallet2.cpp	2021-04-19 23:18:19.787302282 +0900
@@ -7354,8 +7354,6 @@
       }
     }
     */
-    bool b = get_pricing_record(pr, current_height);
-    THROW_WALLET_EXCEPTION_IF(!b, error::wallet_internal_error, "Failed to get pricing record");
     uint32_t fees_version = use_fork_rules(HF_VERSION_OFFSHORE_FEES_V3, 0) ? 3 : use_fork_rules(HF_VERSION_OFFSHORE_FEES_V2, 0) ? 2 : 1;
     bool use_offshore_tx_version = use_fork_rules(HF_VERSION_OFFSHORE_FULL, 0);
     bool r = cryptonote::construct_tx_and_get_tx_key(m_account.get_keys(), m_subaddresses, sd.sources, sd.splitted_dsts, sd.change_dts.addr, sd.extra, ptx.tx, sd.unlock_time, tx_key, additional_tx_keys, current_height, pr, fees_version, use_offshore_tx_version, sd.use_rct, rct_config, m_multisig ? &msout : NULL);
```

and tried to sign a transaction offline.

```
: sign_transfer
Error: Failed to sign transaction: Failed to get height
```

**Comment by crocket** [comment]
With this patch
```
diff -ur haven-offshore-1.3.0c/monero/src/wallet/wallet2.cpp haven-offshore-1.3.0c-new/monero/src/wallet/wallet2.cpp
--- haven-offshore-1.3.0c/monero/src/wallet/wallet2.cpp	2021-04-20 10:53:07.935199076 +0900
+++ haven-offshore-1.3.0c-new/monero/src/wallet/wallet2.cpp	2021-04-20 10:58:38.976725080 +0900
@@ -7354,10 +7354,8 @@
       }
     }
     */
-    bool b = get_pricing_record(pr, current_height);
-    THROW_WALLET_EXCEPTION_IF(!b, error::wallet_internal_error, "Failed to get pricing record");
-    uint32_t fees_version = use_fork_rules(HF_VERSION_OFFSHORE_FEES_V3, 0) ? 3 : use_fork_rules(HF_VERSION_OFFSHORE_FEES_V2, 0) ? 2 : 1;
-    bool use_offshore_tx_version = use_fork_rules(HF_VERSION_OFFSHORE_FULL, 0);
+    uint32_t fees_version = 3;
+    bool use_offshore_tx_version = true;
     bool r = cryptonote::construct_tx_and_get_tx_key(m_account.get_keys(), m_subaddresses, sd.sources, sd.splitted_dsts, sd.change_dts.addr, sd.extra, ptx.tx, sd.unlock_time, tx_key, additional_tx_keys, current_height, pr, fees_version, use_offshore_tx_version, sd.use_rct, rct_config, m_multisig ? &msout : NULL);
     THROW_WALLET_EXCEPTION_IF(!r, error::tx_not_constructed, sd.sources, sd.splitted_dsts, sd.unlock_time, m_nettype);
     // we don't test tx size, because we don't know the current limit, due to not having a blockchain,
```
I can sign XHV transfer offline.

**Comment by neilcoggins** [comment]
Thanks for the suggestion. We are presently resolving offline signing through a variation of your suggested code, which will involve adding the `fees_version` and `use_offshore_tx_version` information to the tx construction data (so that the information is available when signing offline).

This should be included in the next release (1.3.0e), which will contain a number of improvements to the wallet code (both in the CLI and the RPC backend).

**Comment by crocket** [comment]
Perhaps, currency conversions happen to be able to be signed offline, too?

**Comment by neilcoggins** [comment]
Conversions won't be possible - we need to use a pricing record (pulled from the blockchain independently) to verify that the transaction isn't fraudulent. But transfers of XHV and xUSD and xAssets will all be possible offline.

**Comment by crocket** [comment]
Will hardware wallets be able to sign currency conversions?

**Comment by neilcoggins** [comment]
Hardware wallets are on the roadmap - that's all I can say at present.

**Comment by crocket** [comment]
Just curious. How do you secure your XHV?

**Comment by neilcoggins** [comment]
I am happy to converse privately with you, but we are now massively OT for this issue. Please message me or another team member on discord for things unrelated to this report. Thanks.

**Comment by crocket** [comment]
Any news on this?

**Comment by akildemir** [comment]
hi @crocket we had put some fixes in place to be able to properly support this feature pre-xassets fork so it wouldn't need a fork when we fix it.  But haven't had the change to have a look at it since, I will move this task up in the todo list so it should be included in the upcoming updates.

**Comment by Mansarde** [comment]
@crocket Why have you closed this? Just tried to sign offline with the latest CLI and it still didn't work. 😢

**Comment by crocket** [comment]
I didn't close this. Was my account hacked?

**Comment by crocket** [comment]
Wait. haven-offshore is discontinued. It's okay to close this issue. Go to haven-main.

**Comment by Mansarde** [comment]
Oh, sorry, was monitoring this ticket and didn't notice it was in the old repo.
My bad!
