### ISSUE TITLE
Build issue on Ubuntu 16.04

### ISSUE THREAD

**Issue by BKdilse** [haven-protocol-org/haven-offshore#2]
-- Performing Test _fcf_protection=full_c
-- Performing Test _fcf_protection=full_c - Failed
-- Performing Test _fcf_protection=full_cxx
-- Performing Test _fcf_protection=full_cxx - Failed
-- Performing Test _fstack_clash_protection_c
-- Performing Test _fstack_clash_protection_c - Failed
-- Performing Test _fstack_clash_protection_cxx
-- Performing Test _fstack_clash_protection_cxx - Failed
-- Performing Test _mmitigate_rop_c
-- Performing Test _mmitigate_rop_c - Failed
-- Performing Test _mmitigate_rop_cxx
-- Performing Test _mmitigate_rop_cxx - Failed

can provide full log if required.

**Comment by dweab** [comment]
Looks like you might need to upgrade cmake to 3.12

**Comment by BKdilse** [comment]
I'm on cmake version 3.5.1

**Comment by BKdilse** [comment]
Updated version of cmake, thanks for the quick response :)
