### ISSUE TITLE
ubuntu 18.04: Policy "CMP0074" is not known to this version of CMake

### ISSUE THREAD

**Issue by lukasalexander** [haven-protocol-org/haven-offshore#3]
version 1.1.2, default ubuntu 18.04 install.
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
-- CMake version 3.10.2
-- Building without build tag
-- Checking submodules
-- Submodule 'external/miniupnp' is up-to-date
-- Submodule 'external/unbound' is up-to-date
-- Submodule 'external/rapidjson' is up-to-date
-- Submodule 'external/trezor-common' is up-to-date
CMake Error at CMakeLists.txt:203 (cmake_policy):
  Policy "CMP0074" is not known to this version of CMake.

**Comment by goshiz** [comment]
You need to install CMAKE 3.12+ since policy CMP0074 is introduce in cmake 3.12
See https://cmake.org/cmake/help/git-stage/policy/CMP0074.html

```
export CMAKE_VERSION=3.17.0
export CMAKE_VERSION_DOT=v3.17

#Install CMAKE
cd ~
curl -s -O https://cmake.org/files/${CMAKE_VERSION_DOT}/cmake-${CMAKE_VERSION}.tar.gz
tar -xzf cmake-${CMAKE_VERSION}.tar.gz
cd cmake-${CMAKE_VERSION}
./configure
make
make install
mv /usr/bin/cmake /usr/bin/cmake.old
ln -s /usr/local/bin/cmake /usr/bin/
```

**Comment by lukasalexander** [comment]
i know :-).
Might still be worth fixing, since not everybody has root access on their machines, nor is every root user willing to manually link newer binaries into system-wide /usr/bin directories. 
CMake can check if it knows the policy : "if (policy cmp....) .... " etc.

**Comment by lukasalexander** [comment]
Alternatively, might be worth documenting which version of ubuntu/debian/etc is recommended/last tested. I'm also building on 20.04, and so far it's still building.

**Comment by goshiz** [comment]
I mean, you can't build haven with a version prior 3.12. It's a requirement.
we could make a better message, but with a little help of Google, Policy "CMP0074" is not known to this version of CMake is easy to understand.

Requirements are on the front page of the repository, it will build on any Linux if you have the requirements, but we certainly could show on which system we were able to buid ourselves.
