### ISSUE TITLE
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by dahifi** [haven-protocol-org/haven-offshore#6]
Running haven-offshore-linux-glibc-2.29-1.1.2a.zip. My understanding is that glib 2.27 is the version supported by Ubuntu 18. 

I don't see Ubuntu 19 mentioned as a requirement in the docs, so mulling my options here, either download the 2.29 version from [here](http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/) or building from scratch...

**Comment by goshiz** [comment]
Please use glibc2.27 package.
