### ISSUE TITLE
please, anyone, solve this issue when I connected an xmrig minner with my pool I'm having trouble with this issue given below in the screenshot.Thanks

### ISSUE THREAD

**Issue by Iftikhar3Mustafa** [haven-protocol-org/haven-offshore#7]
![Pool miner problems](https://user-images.githubusercontent.com/54815154/99357448-be3ce280-28cd-11eb-91cc-02881f900e0a.png)

**Comment by goshiz** [comment]
Hi, this is a configuration issue, not an issue with the code. Please come by the discord to find help.

**Comment by Iftikhar3Mustafa** [comment]
Please help me, How to solve this problem?
