### ISSUE TITLE
The old wallet cannot be activated with the new one

### ISSUE THREAD

**Issue by guosq02** [haven-protocol-org/haven-offshore#8]
Hello, the old version of the wallet can not be activated on the new version of the wallet, is there any way to solve it?
I tried to use mnemonics to recreate wallets, but I was prompted that I couldn't synchronize my wallet due to inconsistent versions
This is a prompt error message

Error: Daemon uses a different RPC major version (2) than the wallet (3): http://localhost:17750. Either update one of them, or use --allow-mismatched-daemon-version.

**Comment by goshiz** [comment]
Hi, the current desktop vault is not compatible with the new version.
We are currently working on the desktop vault to release it soon.

In the meantime you can use the Web Vault on https://vault.havenprotocol.org/#/ or use a Command Line Interface (CLI) available on the website https://havenprotocol.org/
